services:
  - type: web
    name: todo-app-backend
    runtime: node
    rootDir: Challenge-2/server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://todo-app-frontend-ecru-three.vercel.app
